### ISSUE TITLE
Not using constructor injection

### ISSUE THREAD

**Issue by tripleentendre** [hubert77500/neuer-demo-with-unitest#4]
This isn't super major since spring handles injection for you, but you're also forced to use the spring test runner for your unit tests instead of using the base junit runner in order to inject your mocks into the class you're testing.

**Comment by hubert77500** [comment]
I agree, I am using autowire and Inject across the application, I can inject mock also for testing

**Comment by tripleentendre** [comment]
I'll close this since it's working fine the way it is.
